services:
  app:
    build: .
    ports:
      - "25565:25565"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}
      - REDIS_HOST=redis:6379
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env

  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - vesperis_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    env_file:
      - .env
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} 
      --aclfile /data/redis.acl
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - vesperis_redis:/data
    entrypoint: >
      sh -c "echo 'user ${REDIS_USER} on >${REDIS_PASSWORD} ~* allcommands' > /data/redis.acl &&
      exec redis-server --requirepass '${REDIS_PASSWORD}' --aclfile /data/redis.acl"

volumes:
  vesperis_mysql:
  vesperis_redis: